enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
compression-level = 9                # module zip compression level

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Youtube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "revanced/revanced-cli"
rv-brand = "anddea ReVanced"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Hide Shorts dimming' 'MaterialYou'"
patcher-args = "-e 'Custom branding name for YouTube' -OappName=Youtube"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "revanced/revanced-cli"
rv-brand = "anddea ReVanced"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Disable music video in album' 'Hide overlay filter' 'Hide player overlay filter'"
patcher-args = "-e 'Custom branding name for YouTube Music' -OappNameNotification='Youtube Music' -OappNameLauncher='Youtube Music'"

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
version = "2025.05.1"
patches-source = "anddea/revanced-patches"
cli-source = "revanced/revanced-cli"
rv-brand = "anddea ReVanced"
patcher-args = "-e 'Custom branding name for Reddit' -OappName=Reddit"

[Twitch]
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[TikTok]
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"
